const paths={golden:"../golden_dataset.json",answers:"../artifacts/actual_answers.json",benchmark:"../artifacts/benchmark_results.json"};
const state={cases:[],current:null,offset:0};
const metrics=[["Faithfulness","faithfulness"],["Relevance","relevance"],["Completeness","completeness"],["Context Recall","context_recall"],["Context Precision","context_precision"]];
const $=(selector)=>document.querySelector(selector);
async function loadArtifacts(){const [golden,answers,benchmark]=await Promise.all(Object.values(paths).map((path)=>fetch(path).then((response)=>{if(!response.ok)throw new Error("Could not load "+path);return response.json()})));const answerById=new Map(answers.answers.map((item)=>[item.id,item]));const benchmarkById=new Map(benchmark.results.map((item)=>[item.id,item]));state.cases=golden.qa_pairs.map((gold)=>({...gold,...benchmarkById.get(gold.id),retrieved_contexts:answerById.get(gold.id)?.retrieved_contexts??[]}));const summary=benchmark.summary;const passRate=Math.round(summary.pass_rate*100);$("#side-pass-rate").textContent=passRate+"%";$("#side-pass-copy").textContent=summary.passed+" of "+summary.total+" cases passed";$("#side-progress").style.width=passRate+"%";renderSuggestions();selectCase(state.cases.find((item)=>item.id==="E01")||state.cases[0])}
function renderSuggestions(){const grid=$("#suggestion-grid");const visible=state.cases.slice(state.offset,state.offset+4);grid.replaceChildren();visible.forEach((item)=>{const button=document.createElement("button");button.className="suggestion";button.type="button";button.innerHTML="<span class='suggestion-meta'><span>"+item.id+"</span><span>"+item.difficulty+"</span></span><span>"+item.question+"</span>";button.addEventListener("click",()=>selectCase(item));grid.append(button)})}
function selectCase(item){if(!item)return;state.current=item;$("#welcome-state").hidden=true;$("#conversation").hidden=false;$("#case-id").textContent=item.id;$("#question-text").textContent=item.question;$("#answer-text").textContent=item.actual_answer||"No saved answer is available.";$("#case-pill").textContent=item.id;$("#overall-score").textContent=formatScore(item.overall);$("#pass-badge").textContent=item.passed?"Passed":"Needs review";$("#pass-badge").className="result-badge "+(item.passed?"result-badge--pass":"result-badge--fail");$("#failure-type").textContent=item.failure_type||"none";$("#failure-hint").textContent=failureHint(item);$("#evidence-list").hidden=true;$("#evidence-toggle").innerHTML="<span>⌘</span> View retrieved evidence";renderMetrics(item);renderEvidence(item);document.querySelector(".main-pane").scrollTo({top:0,behavior:"smooth"})}
function renderMetrics(item){const list=$("#metric-list");list.replaceChildren();metrics.forEach(([label,key])=>{const row=$("#metric-template").content.cloneNode(true);row.querySelector(".metric-name").textContent=label;row.querySelector(".metric-value").textContent=formatScore(item[key]);row.querySelector(".metric-track span").style.width=Math.max(0,Math.min(1,item[key]??0))*100+"%";list.append(row)})}
function renderEvidence(item){const list=$("#evidence-list");list.replaceChildren();item.retrieved_contexts.forEach((context,index)=>{const card=document.createElement("article");card.className="evidence-card";card.innerHTML="<header><span>Rank "+(index+1)+" · "+context.chunk_id+"</span><span>"+context.source_doc+"</span></header><p></p>";card.querySelector("p").textContent=context.text;list.append(card)})}
function failureHint(item){if(item.passed)return"This case clears all three answer-score thresholds.";if(item.failure_type==="hallucination")return"Inspect answer claims against the gold context and the retrieved trace.";if(item.failure_type==="irrelevant")return"Compare question terms with the answer before changing retrieval.";if(item.failure_type==="incomplete")return"Check whether required policy details were retrieved and expressed.";return"Inspect the trace. This label indicates an answer-side issue after threshold checks."}
function formatScore(value){return typeof value==="number"?value.toFixed(3):"—"}
$("#shuffle-button").addEventListener("click",()=>{state.offset=(state.offset+4)%state.cases.length;renderSuggestions()});
$("#evidence-toggle").addEventListener("click",()=>{const list=$("#evidence-list");list.hidden=!list.hidden;$("#evidence-toggle").innerHTML=list.hidden?"<span>⌘</span> View retrieved evidence":"<span>⌃</span> Hide retrieved evidence"});
$("#composer").addEventListener("submit",(event)=>{event.preventDefault();const query=$("#question-input").value.trim().toLowerCase();if(!query)return;const words=query.split(/\s+/);const match=state.cases.map((item)=>({item,score:words.filter((word)=>item.question.toLowerCase().includes(word)).length})).sort((a,b)=>b.score-a.score)[0];if(match?.score){selectCase(match.item);$("#question-input").value=""}else{$("#question-input").setCustomValidity("No saved benchmark case matches that search.");$("#question-input").reportValidity();$("#question-input").setCustomValidity("")}});
$("#metrics-nav").addEventListener("click",()=>$("#inspector").scrollIntoView({behavior:"smooth"}));
$("#theme-button").addEventListener("click",()=>document.body.classList.toggle("high-contrast"));
loadArtifacts().catch((error)=>{console.error(error);$("#welcome-state").innerHTML="<div class='welcome-orbit'>!</div><h2>Start the local demo server</h2><p>The app loads benchmark artifacts with fetch. Run python3 -m http.server 8000 from the repository root, then open http://localhost:8000/demo_ui/.</p>"});
